export const paths = {
  HOME: "/",
  PRODUCTS: "/san-pham",
  CHECKOUT: "/thanh-toan",
  LOGIN: "/dang-nhap",
  REGISTER: "/dang-ky",
  ADMIN: "/admin",
  DASHBOARD: "/bang-dieu-khien",
  MANAGE_PRODUCTS: "/quan-ly-san-pham",
  MANAGE_CATEGORIES: "/quan-ly-danh-muc",
  MANAGE_ORDERS: "/quan-ly-don-hang",
  MANAGE_USERS: "/quan-ly-user",
  MANAGE_BLOGS: "/quan-ly-blog",
  PROFILE: "/ca-nhan",
  INFO: "/thong-tin",
  ORDERS: "/don-hang",
  BLOGS: "/blogs",
  SEARCH_RESULT: "/ket-qua-tim-kiem",
};
